@IsTest
private class brMainNavMenuAltCtrlTest {
    @TestSetup
    static void setup() {
        User testUser = brTestDataFactory.createTestStandardProfileUser();
        System.assertEquals('sysuserbaker@test.com', testUser.UserName, 'wrong username');
    }

    @isTest
    static void testGetLabels() {
        Test.startTest();

        User testUser = [SELECT Id, UserName FROM User WHERE UserName = 'sysuserbaker@test.com'];

        System.assertEquals('sysuserbaker@test.com', testUser.UserName, 'wrong username');

        System.runAs(testUser) {
            List<String> labels = brMainNavMenuAltCtrl.getLabels();
            System.assertEquals('Test', labels[0], 'wrong labels');
        }

        Test.stopTest();

    }
}